//
//  AddMoneyCardExpirationViewController.m
//  Aggregate
//
//  Created by Netmobo on 9/8/10.
//  Copyright 2010 Aurisoft. All rights reserved.
//

#import "AddMoneyCardExpirationViewController.h"
#import "Model.h"
#import "Country.h"
#import "State.h"

#define CURRENT_CALENDAR [NSCalendar currentCalendar]
#define DATE_COMPONENTS (NSYearCalendarUnit| NSMonthCalendarUnit | NSDayCalendarUnit | NSWeekCalendarUnit |  NSHourCalendarUnit | NSMinuteCalendarUnit | NSSecondCalendarUnit | NSWeekdayCalendarUnit | NSWeekdayOrdinalCalendarUnit)

@implementation AddMoneyCardExpirationViewController

@synthesize whichOne, whichOneLabel;
@synthesize expirationPicker;
@synthesize monthArray, yearArray;
@synthesize countryArray;
@synthesize cardTypeArray;
@synthesize stateArray;

- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil whichOne:(NSString *) aWhichOne {
    if ((self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil])) {
        // Custom initialization
		[self setWhichOne:aWhichOne];
    }
    return self;
}

- (void) doAction {
	Model *model = [Model sharedModel];
	if ([whichOne isEqualToString:@"Country"]) {
		NSInteger row = [expirationPicker selectedRowInComponent:0];
		[model setCurrentCardCountry:[[[countryArray objectAtIndex:row] name] capitalizedString] ];
		[model setCurrentCardCountryCode:[[countryArray objectAtIndex:row] countryCode] ];
		
	} else if ([whichOne isEqualToString:@"Expiration"]) {
		// convert month word into 2-digit integer:
		NSInteger rowMonth = [expirationPicker selectedRowInComponent:0];
		int monthInt = rowMonth + 1;
		NSString *month;
		if (monthInt > 9) {
			month = [NSString stringWithFormat:@"%i", monthInt];
		} else {
			month = [NSString stringWithFormat:@"0%i", monthInt];
		}
		
//		[model setCurrentCardMonth:[monthArray objectAtIndex:rowMonth]];
		[model setCurrentCardMonth:month];
		
		NSInteger rowYear = [expirationPicker selectedRowInComponent:1];
		[model setCurrentCardYear:[yearArray objectAtIndex:rowYear]];
		
	} else if([whichOne isEqualToString:@"State"]) {
		NSInteger row = [expirationPicker selectedRowInComponent:0];
		[model setState:[[stateArray objectAtIndex:row] stateCode] ];
	} else {
		NSInteger row = [expirationPicker selectedRowInComponent:0];
		[model setCurrentCardType:[cardTypeArray objectAtIndex:row]];
		
	}
	
	[self.navigationController popViewControllerAnimated:YES];
}

// Implement viewDidLoad to do additional setup after loading the view, typically from a nib.
- (void)viewDidLoad {
    [super viewDidLoad];
	
	whichOneLabel.text = whichOne;
	
	UIBarButtonItem *doneButton = [[UIBarButtonItem alloc] initWithTitle:@"Done" style:UIBarButtonItemStyleDone target:self action:@selector(doAction)];
	self.navigationItem.rightBarButtonItem = doneButton;
	[doneButton release];
	
	if ([whichOne isEqualToString:@"Country"]) {
		Country *country;
		self.countryArray = [[[NSMutableArray alloc] init] autorelease];
		
		country = [[Country alloc] init];
		[country setName:@"UNITED STATES"];
		[country setCountryCode:@"US"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		
		country = [[Country alloc] init];
		[country setName:@"AFGHANISTAN"];
		[country setCountryCode:@"AF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ALAND ISLANDS"];
		[country setCountryCode:@"AX"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ALBANIA"];
		[country setCountryCode:@"AL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ALGERIA"];
		[country setCountryCode:@"DZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"AMERICAN SAMOA"];
		[country setCountryCode:@"AS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ANDORRA"];
		[country setCountryCode:@"AD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ANGOLA"];
		[country setCountryCode:@"AO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ANGUILLA"];
		[country setCountryCode:@"AI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ANTARCTICA"];
		[country setCountryCode:@"AQ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ANTIGUA AND BARBUDA"];
		[country setCountryCode:@"AG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ARGENTINA"];
		[country setCountryCode:@"AR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ARMENIA"];
		[country setCountryCode:@"AM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ARUBA"];
		[country setCountryCode:@"AW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"AUSTRALIA"];
		[country setCountryCode:@"AU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"AUSTRIA"];
		[country setCountryCode:@"AT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"AZERBAIJAN"];
		[country setCountryCode:@"AZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BAHAMAS"];
		[country setCountryCode:@"BS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BAHRAIN"];
		[country setCountryCode:@"BH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BANGLADESH"];
		[country setCountryCode:@"BD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BARBADOS"];
		[country setCountryCode:@"BB"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BELARUS"];
		[country setCountryCode:@"BY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BELGIUM"];
		[country setCountryCode:@"BE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BELIZE"];
		[country setCountryCode:@"BZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BENIN"];
		[country setCountryCode:@"BJ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BERMUDA"];
		[country setCountryCode:@"BM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BHUTAN"];
		[country setCountryCode:@"BT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BOLIVIA, PLURINATIONAL STATE OF"];
		[country setCountryCode:@"BO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BOSNIA AND HERZEGOVINA"];
		[country setCountryCode:@"BA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BOTSWANA"];
		[country setCountryCode:@"BW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BOUVET ISLAND"];
		[country setCountryCode:@"BV"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BRAZIL"];
		[country setCountryCode:@"BR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BRITISH INDIAN OCEAN TERRITORY"];
		[country setCountryCode:@"IO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BRUNEI DARUSSALAM"];
		[country setCountryCode:@"BN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BULGARIA"];
		[country setCountryCode:@"BG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BURKINA FASO"];
		[country setCountryCode:@"BF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"BURUNDI"];
		[country setCountryCode:@"BI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CAMBODIA"];
		[country setCountryCode:@"KH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CAMEROON"];
		[country setCountryCode:@"CM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CANADA"];
		[country setCountryCode:@"CA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CAPE VERDE"];
		[country setCountryCode:@"CV"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CAYMAN ISLANDS"];
		[country setCountryCode:@"KY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CENTRAL AFRICAN REPUBLIC"];
		[country setCountryCode:@"CF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CHAD"];
		[country setCountryCode:@"TD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CHILE"];
		[country setCountryCode:@"CL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CHINA"];
		[country setCountryCode:@"CN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CHRISTMAS ISLAND"];
		[country setCountryCode:@"CX"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"COCOS (KEELING) ISLANDS"];
		[country setCountryCode:@"CC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"COLOMBIA"];
		[country setCountryCode:@"CO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"COMOROS"];
		[country setCountryCode:@"KM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CONGO"];
		[country setCountryCode:@"CG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CONGO, THE DEMOCRATIC REPUBLIC OF THE"];
		[country setCountryCode:@"CD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"COOK ISLANDS"];
		[country setCountryCode:@"CK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"COSTA RICA"];
		[country setCountryCode:@"CR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"C•TE D'IVOIRE"];
		[country setCountryCode:@"CI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CROATIA"];
		[country setCountryCode:@"HR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CUBA"];
		[country setCountryCode:@"CU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CYPRUS"];
		[country setCountryCode:@"CY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"CZECH REPUBLIC"];
		[country setCountryCode:@"CZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"DENMARK"];
		[country setCountryCode:@"DK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"DJIBOUTI"];
		[country setCountryCode:@"DJ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"DOMINICA"];
		[country setCountryCode:@"DM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"DOMINICAN REPUBLIC"];
		[country setCountryCode:@"DO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ECUADOR"];
		[country setCountryCode:@"EC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"EGYPT"];
		[country setCountryCode:@"EG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"EL SALVADOR"];
		[country setCountryCode:@"SV"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"EQUATORIAL GUINEA"];
		[country setCountryCode:@"GQ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ERITREA"];
		[country setCountryCode:@"ER"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ESTONIA"];
		[country setCountryCode:@"EE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ETHIOPIA"];
		[country setCountryCode:@"ET"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FALKLAND ISLANDS (MALVINAS)"];
		[country setCountryCode:@"FK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FAROE ISLANDS"];
		[country setCountryCode:@"FO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FIJI"];
		[country setCountryCode:@"FJ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FINLAND"];
		[country setCountryCode:@"FI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FRANCE"];
		[country setCountryCode:@"FR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FRENCH GUIANA"];
		[country setCountryCode:@"GF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FRENCH POLYNESIA"];
		[country setCountryCode:@"PF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"FRENCH SOUTHERN TERRITORIES"];
		[country setCountryCode:@"TF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GABON"];
		[country setCountryCode:@"GA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GAMBIA"];
		[country setCountryCode:@"GM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GEORGIA"];
		[country setCountryCode:@"GE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GERMANY"];
		[country setCountryCode:@"DE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GHANA"];
		[country setCountryCode:@"GH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GIBRALTAR"];
		[country setCountryCode:@"GI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GREECE"];
		[country setCountryCode:@"GR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GREENLAND"];
		[country setCountryCode:@"GL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GRENADA"];
		[country setCountryCode:@"GD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUADELOUPE"];
		[country setCountryCode:@"GP"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUAM"];
		[country setCountryCode:@"GU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUATEMALA"];
		[country setCountryCode:@"GT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUERNSEY"];
		[country setCountryCode:@"GG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUINEA"];
		[country setCountryCode:@"GN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUINEA-BISSAU"];
		[country setCountryCode:@"GW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"GUYANA"];
		[country setCountryCode:@"GY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"HAITI"];
		[country setCountryCode:@"HT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"HEARD ISLAND AND MCDONALD ISLANDS"];
		[country setCountryCode:@"HM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"HOLY SEE (VATICAN CITY STATE)"];
		[country setCountryCode:@"VA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"HONDURAS"];
		[country setCountryCode:@"HN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"HONG KONG"];
		[country setCountryCode:@"HK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"HUNGARY"];
		[country setCountryCode:@"HU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ICELAND"];
		[country setCountryCode:@"IS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"INDIA"];
		[country setCountryCode:@"IN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"INDONESIA"];
		[country setCountryCode:@"ID"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"IRAN, ISLAMIC REPUBLIC OF"];
		[country setCountryCode:@"IR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"IRAQ"];
		[country setCountryCode:@"IQ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"IRELAND"];
		[country setCountryCode:@"IE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ISLE OF MAN"];
		[country setCountryCode:@"IM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ISRAEL"];
		[country setCountryCode:@"IL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ITALY"];
		[country setCountryCode:@"IT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"JAMAICA"];
		[country setCountryCode:@"JM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"JAPAN"];
		[country setCountryCode:@"JP"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"JERSEY"];
		[country setCountryCode:@"JE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"JORDAN"];
		[country setCountryCode:@"JO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KAZAKHSTAN"];
		[country setCountryCode:@"KZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KENYA"];
		[country setCountryCode:@"KE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KIRIBATI"];
		[country setCountryCode:@"KI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"];
		[country setCountryCode:@"KP"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KOREA, REPUBLIC OF"];
		[country setCountryCode:@"KR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KUWAIT"];
		[country setCountryCode:@"KW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"KYRGYZSTAN"];
		[country setCountryCode:@"KG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LAO PEOPLE'S DEMOCRATIC REPUBLIC"];
		[country setCountryCode:@"LA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LATVIA"];
		[country setCountryCode:@"LV"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LEBANON"];
		[country setCountryCode:@"LB"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LESOTHO"];
		[country setCountryCode:@"LS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LIBERIA"];
		[country setCountryCode:@"LR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LIBYAN ARAB JAMAHIRIYA"];
		[country setCountryCode:@"LY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LIECHTENSTEIN"];
		[country setCountryCode:@"LI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LITHUANIA"];
		[country setCountryCode:@"LT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"LUXEMBOURG"];
		[country setCountryCode:@"LU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MACAO"];
		[country setCountryCode:@"MO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"];
		[country setCountryCode:@"MK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MADAGASCAR"];
		[country setCountryCode:@"MG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MALAWI"];
		[country setCountryCode:@"MW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MALAYSIA"];
		[country setCountryCode:@"MY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MALDIVES"];
		[country setCountryCode:@"MV"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MALI"];
		[country setCountryCode:@"ML"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MALTA"];
		[country setCountryCode:@"MT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MARSHALL ISLANDS"];
		[country setCountryCode:@"MH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MARTINIQUE"];
		[country setCountryCode:@"MQ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MAURITANIA"];
		[country setCountryCode:@"MR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MAURITIUS"];
		[country setCountryCode:@"MU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MAYOTTE"];
		[country setCountryCode:@"YT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MEXICO"];
		[country setCountryCode:@"MX"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MICRONESIA, FEDERATED STATES OF"];
		[country setCountryCode:@"FM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MOLDOVA, REPUBLIC OF"];
		[country setCountryCode:@"MD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MONACO"];
		[country setCountryCode:@"MC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MONGOLIA"];
		[country setCountryCode:@"MN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MONTENEGRO"];
		[country setCountryCode:@"ME"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MONTSERRAT"];
		[country setCountryCode:@"MS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MOROCCO"];
		[country setCountryCode:@"MA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MOZAMBIQUE"];
		[country setCountryCode:@"MZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"MYANMAR"];
		[country setCountryCode:@"MM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NAMIBIA"];
		[country setCountryCode:@"NA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NAURU"];
		[country setCountryCode:@"NR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NEPAL"];
		[country setCountryCode:@"NP"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NETHERLANDS"];
		[country setCountryCode:@"NL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NETHERLANDS ANTILLES"];
		[country setCountryCode:@"AN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NEW CALEDONIA"];
		[country setCountryCode:@"NC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NEW ZEALAND"];
		[country setCountryCode:@"NZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NICARAGUA"];
		[country setCountryCode:@"NI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NIGER"];
		[country setCountryCode:@"NE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NIGERIA"];
		[country setCountryCode:@"NG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NIUE"];
		[country setCountryCode:@"NU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NORFOLK ISLAND"];
		[country setCountryCode:@"NF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NORTHERN MARIANA ISLANDS"];
		[country setCountryCode:@"MP"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"NORWAY"];
		[country setCountryCode:@"NO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"OMAN"];
		[country setCountryCode:@"OM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PAKISTAN"];
		[country setCountryCode:@"PK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PALAU"];
		[country setCountryCode:@"PW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PALESTINIAN TERRITORY, OCCUPIED"];
		[country setCountryCode:@"PS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PANAMA"];
		[country setCountryCode:@"PA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PAPUA NEW GUINEA"];
		[country setCountryCode:@"PG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PARAGUAY"];
		[country setCountryCode:@"PY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PERU"];
		[country setCountryCode:@"PE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PHILIPPINES"];
		[country setCountryCode:@"PH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PITCAIRN"];
		[country setCountryCode:@"PN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"POLAND"];
		[country setCountryCode:@"PL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PORTUGAL"];
		[country setCountryCode:@"PT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"PUERTO RICO"];
		[country setCountryCode:@"PR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"QATAR"];
		[country setCountryCode:@"QA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"R"];
		[country setCountryCode:@""];
		[country setName:@"R•UNION"];
		[country setCountryCode:@"RE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ROMANIA"];
		[country setCountryCode:@"RO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"RUSSIAN FEDERATION"];
		[country setCountryCode:@"RU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"RWANDA"];
		[country setCountryCode:@"RW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT BARTH•LEMY"];
		[country setCountryCode:@"BL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"];
		[country setCountryCode:@"SH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT KITTS AND NEVIS"];
		[country setCountryCode:@"KN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT LUCIA"];
		[country setCountryCode:@"LC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT MARTIN"];
		[country setCountryCode:@"MF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT PIERRE AND MIQUELON"];
		[country setCountryCode:@"PM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAINT VINCENT AND THE GRENADINES"];
		[country setCountryCode:@"VC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAMOA"];
		[country setCountryCode:@"WS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAN MARINO"];
		[country setCountryCode:@"SM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAO TOME AND PRINCIPE"];
		[country setCountryCode:@"ST"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SAUDI ARABIA"];
		[country setCountryCode:@"SA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SENEGAL"];
		[country setCountryCode:@"SN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SERBIA"];
		[country setCountryCode:@"RS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SEYCHELLES"];
		[country setCountryCode:@"SC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SIERRA LEONE"];
		[country setCountryCode:@"SL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SINGAPORE"];
		[country setCountryCode:@"SG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SLOVAKIA"];
		[country setCountryCode:@"SK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SLOVENIA"];
		[country setCountryCode:@"SI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SOLOMON ISLANDS"];
		[country setCountryCode:@"SB"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SOMALIA"];
		[country setCountryCode:@"SO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SOUTH AFRICA"];
		[country setCountryCode:@"ZA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"];
		[country setCountryCode:@"GS"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SPAIN"];
		[country setCountryCode:@"ES"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SRI LANKA"];
		[country setCountryCode:@"LK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SUDAN"];
		[country setCountryCode:@"SD"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SURINAME"];
		[country setCountryCode:@"SR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SVALBARD AND JAN MAYEN"];
		[country setCountryCode:@"SJ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SWAZILAND"];
		[country setCountryCode:@"SZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SWEDEN"];
		[country setCountryCode:@"SE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SWITZERLAND"];
		[country setCountryCode:@"CH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"SYRIAN ARAB REPUBLIC"];
		[country setCountryCode:@"SY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TAIWAN, PROVINCE OF CHINA"];
		[country setCountryCode:@"TW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TAJIKISTAN"];
		[country setCountryCode:@"TJ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TANZANIA, UNITED REPUBLIC OF"];
		[country setCountryCode:@"TZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"THAILAND"];
		[country setCountryCode:@"TH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TIMOR-LESTE"];
		[country setCountryCode:@"TL"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TOGO"];
		[country setCountryCode:@"TG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TOKELAU"];
		[country setCountryCode:@"TK"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TONGA"];
		[country setCountryCode:@"TO"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TRINIDAD AND TOBAGO"];
		[country setCountryCode:@"TT"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TUNISIA"];
		[country setCountryCode:@"TN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TURKEY"];
		[country setCountryCode:@"TR"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TURKMENISTAN"];
		[country setCountryCode:@"TM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TURKS AND CAICOS ISLANDS"];
		[country setCountryCode:@"TC"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"TUVALU"];
		[country setCountryCode:@"TV"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"UGANDA"];
		[country setCountryCode:@"UG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"UKRAINE"];
		[country setCountryCode:@"UA"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"UNITED ARAB EMIRATES"];
		[country setCountryCode:@"AE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"UNITED KINGDOM"];
		[country setCountryCode:@"GB"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		
		country = [[Country alloc] init];
		[country setName:@"UNITED STATES MINOR OUTLYING ISLANDS"];
		[country setCountryCode:@"UM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"URUGUAY"];
		[country setCountryCode:@"UY"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"UZBEKISTAN"];
		[country setCountryCode:@"UZ"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"VANUATU"];
		[country setCountryCode:@"VU"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"VATICAN CITY STATE"];
		[country setCountryCode:@"see HOLY SEE"];
		[country setName:@"VENEZUELA, BOLIVARIAN REPUBLIC OF"];
		[country setCountryCode:@"VE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"VIET NAM"];
		[country setCountryCode:@"VN"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"VIRGIN ISLANDS, BRITISH"];
		[country setCountryCode:@"VG"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"VIRGIN ISLANDS, U.S."];
		[country setCountryCode:@"VI"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"WALLIS AND FUTUNA"];
		[country setCountryCode:@"WF"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"WESTERN SAHARA"];
		[country setCountryCode:@"EH"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"YEMEN"];
		[country setCountryCode:@"YE"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ZAMBIA"];
		[country setCountryCode:@"ZM"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		country = [[Country alloc] init];
		[country setName:@"ZIMBABWE"];
		[country setCountryCode:@"ZW"];
		[countryArray addObject:country];
		[country release];
		country = nil;
		
		
	} else if ([whichOne isEqualToString:@"Expiration"]) {
		self.monthArray = [[[NSArray alloc] initWithObjects:@"Jan", @"Feb", @"Mar", @"Apr", @"May", @"June", 
						   @"July", @"Aug", @"Sep", @"Oct", @"Nov", @"Dec", nil] autorelease];
		NSDateComponents *components = [CURRENT_CALENDAR components:DATE_COMPONENTS fromDate:[NSDate date]];

		yearArray = [[NSMutableArray alloc] init];
		int tempYear = [components year];
		for (int x = tempYear; x < (tempYear + 10); x++) {
			[yearArray addObject:[NSString stringWithFormat:@"%i", x]];
		}
	} else if ([whichOne isEqualToString:@"State"]) {
		State *state;
		self.stateArray = [[[NSMutableArray alloc] init] autorelease];
		Model *model = [Model sharedModel];
		
		if ([[model currentCardCountryCode] isEqualToString:@"CA"]) {
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"AB"];
			[state setStateName:@"Alberta"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"BC"];
			[state setStateName:@"British Columbia"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"MB"];
			[state setStateName:@"Manitoba"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"NB"];
			[state setStateName:@"New Brunswick"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"NL"];
			[state setStateName:@"Newfoundland"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"NS"];
			[state setStateName:@"Nova Scotia"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"NU"];
			[state setStateName:@"Nunavut"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"ON"];
			[state setStateName:@"Ontario"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"PE"];
			[state setStateName:@"Prince Edward Island"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"QC"];
			[state setStateName:@"Quebec"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"SK"];
			[state setStateName:@"Saskatchewan"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"NT"];
			[state setStateName:@"Northwest Territories"];
			[stateArray addObject:state];
			[state release];
			state = nil;
			state = [[State alloc] init];
			[state setCountryCode:@"CA"];
			[state setStateCode:@"YT"];
			[state setStateName:@"Yukon Territory"];
			[stateArray addObject:state];
			[state release];
			state = nil;
		} else {
		
			state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AA"];
			[state setStateName:@"Armed Forces Americas"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AE"];
			[state setStateName:@"Armed Forces Europe, Middle East, & Canada"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AK"];
			[state setStateName:@"Alaska"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AL"];
			[state setStateName:@"Alabama"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AP"];
			[state setStateName:@"Armed Forces Pacific"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AR"];
			[state setStateName:@"Arkansas"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AS"];
			[state setStateName:@"American Samoa"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"AZ"];
			[state setStateName:@"Arizona"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"CA"];
			[state setStateName:@"California"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"CO"];
			[state setStateName:@"Colorado"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"CT"];
			[state setStateName:@"Connecticut"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"DC"];
			[state setStateName:@"District of Columbia"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"DE"];
			[state setStateName:@"Delaware"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"FL"];
			[state setStateName:@"Florida"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"FM"];
			[state setStateName:@"Federated States of Micronesia"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"GA"];
			[state setStateName:@"Georgia"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"GU"];
			[state setStateName:@"Guam"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"HI"];
			[state setStateName:@"Hawaii"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"IA"];
			[state setStateName:@"Iowa"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"ID"];
			[state setStateName:@"Idaho"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"IL"];
			[state setStateName:@"Illinois"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"IN"];
			[state setStateName:@"Indiana"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"KS"];
			[state setStateName:@"Kansas"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"KY"];
			[state setStateName:@"Kentucky"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"LA"];
			[state setStateName:@"Louisiana"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MA"];
			[state setStateName:@"Massachusetts"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MD"];
			[state setStateName:@"Maryland"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"ME"];
			[state setStateName:@"Maine"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MH"];
			[state setStateName:@"Marshall Islands"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MI"];
			[state setStateName:@"Michigan"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MN"];
			[state setStateName:@"Minnesota"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MO"];
			[state setStateName:@"Missouri"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MP"];
			[state setStateName:@"Northern Mariana Islands"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MS"];
			[state setStateName:@"Mississippi"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"MT"];
			[state setStateName:@"Montana"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NC"];
			[state setStateName:@"North Carolina"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"ND"];
			[state setStateName:@"North Dakota"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NE"];
			[state setStateName:@"Nebraska"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NH"];
			[state setStateName:@"New Hampshire"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NJ"];
			[state setStateName:@"New Jersey"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NM"];
			[state setStateName:@"New Mexico"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NV"];
			[state setStateName:@"Nevada"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"NY"];
			[state setStateName:@"New York"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"OH"];
			[state setStateName:@"Ohio"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"OK"];
			[state setStateName:@"Oklahoma"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"OR"];
			[state setStateName:@"Oregon"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"PA"];
			[state setStateName:@"Pennsylvania"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"PR"];
			[state setStateName:@"Puerto Rico"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"PW"];
			[state setStateName:@"Palau"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"RI"];
			[state setStateName:@"Rhode Island"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"SC"];
			[state setStateName:@"South Carolina"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"SD"];
			[state setStateName:@"South Dakota"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"TN"];
			[state setStateName:@"Tennessee"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"TX"];
			[state setStateName:@"Texas"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"UT"];
			[state setStateName:@"Utah"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"VA"];
			[state setStateName:@"Virginia"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"VI"];
			[state setStateName:@"Virgin Islands"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"VT"];
			[state setStateName:@"Vermont"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"WA"];
			[state setStateName:@"Washington"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"WV"];
			[state setStateName:@"West Virginia"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"WI"];
			[state setStateName:@"Wisconsin"];
			[stateArray addObject:state];
			[state release];
			state = nil;state = [[State alloc] init];
			[state setCountryCode:@"US"];
			[state setStateCode:@"WY"];
			[state setStateName:@"Wyoming"];
			[stateArray addObject:state];
			[state release];
			state = nil;
		}
		
	} else {
		self.cardTypeArray = [[[NSArray alloc] initWithObjects:@"Visa", @"Mastercard", @"AmEx", @"Discovery", nil] autorelease];
	}
	
	
}


/*
// Override to allow orientations other than the default portrait orientation.
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    // Return YES for supported orientations
    return (interfaceOrientation == UIInterfaceOrientationPortrait);
}
*/

- (void)didReceiveMemoryWarning {
    // Releases the view if it doesn't have a superview.
    [super didReceiveMemoryWarning];
    
    // Release any cached data, images, etc that aren't in use.
}

- (void)viewDidUnload {
    [super viewDidUnload];
    // Release any retained subviews of the main view.
    // e.g. self.myOutlet = nil;
}


- (void)dealloc {
	[stateArray release];
	[cardTypeArray release];
	[whichOne release];
	[whichOneLabel release];
	[countryArray release];
	[monthArray release];
	[yearArray release];
	[expirationPicker release];
	
    [super dealloc];
}

#pragma mark -
#pragma mark Picker Data Source Methods

- (NSInteger)numberOfComponentsInPickerView:(UIPickerView *)pickerView {
	if ([whichOne isEqualToString:@"Expiration"]) {
		return 2;
	} else {
		return 1;
	}
}

- (NSInteger)pickerView:(UIPickerView *)pickerView numberOfRowsInComponent:(NSInteger)component {
	if ([whichOne isEqualToString:@"Country"]) {
		return [countryArray count];
	} else if ([whichOne isEqualToString:@"Expiration"]) {
		if (component == 0) {
			return [monthArray count];
		} else {
			return [yearArray count];
		}
	} else if ([whichOne isEqualToString:@"Card Type"]) {
		return [cardTypeArray count];
	} else if ([whichOne isEqualToString:@"State"]) { 
		return [stateArray count];
	} else {
		return 1;
	}
}

#pragma mark Picker Delegate Methods
- (NSString *) pickerView:(UIPickerView *)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component {
	if ([whichOne isEqualToString:@"Country"]) {
		return [[[countryArray objectAtIndex:row] name] capitalizedString];
	} else if ([whichOne isEqualToString:@"Expiration"]) {
		if (component == 0) {
			return [monthArray objectAtIndex:row];
		} else {
			return [yearArray objectAtIndex:row];
		}
	} else if ([whichOne isEqualToString:@"Card Type"]) {
		return [cardTypeArray objectAtIndex:row];
	} else if ([whichOne isEqualToString:@"State"]) {
		return [[stateArray objectAtIndex:row] stateName];
	} else {
		return @"error";
	}
}

@end
